---
- hosts: all
  become: yes

  tasks:
    - name: Create Docker Service
      shell: docker service create --name mynginx --replicas 3 --constraint node.role==worker --with-registry-auth -p 8088:80 nginx
